### ISSUE TITLE
Comprehensive ablation study of all tokeniser parameters

### ISSUE THREAD

**Issue by dhbrojas** [rojas-diego/tokengeex#12]
### Description

A lot of features have been baked in TokenGeeX without any actual benchmarking or comparison against baselines or previous implementations of TokenGeeX.

For every added heuristic, feature or rule benchmark it!!!

Measure compression and the frequency distribution of tokens on a held-out dataset.

**Comment by otodak** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
littlefish0331, @ilwwmmh, @Wushiyii, @dem0nix, @HugoZou, @R-Niagra, @kukuma210, @coderaky, @epogrebnyak, @codewithmitesh, @cisan86, @ronnin, @IngeniousArtist, @yashbhuva, @isahitya, @amankumaar, @progmatic-99, @jamzynoo, @shiyijun0, @cmxss, @zengzhen1994, @HeinKhantZaw, @CGodl, @ttllmm, @henrylao, @wind3, @nonameb3, @niskhakov, @thomcosta, @sobitd, @trungle15, @michaelchiche, @sinornis, @chi-bes, @JayamaniJai, @poppinlr, @Guillecaba, @AndyJoo, @kinalmehta, @saumilvachheta, @alvaroserrrano, @Prathamesh-V-Kirad, @nixdonut, @senabi, @wenhongming, @aniforverizon, @shrshk, @fernando-gap, @huzilonghu, @Orob0rus
