### ISSUE TITLE
Add support for vocabulary "extension packs"

### ISSUE THREAD

**Issue by dhbrojas** [rojas-diego/tokengeex#3]
### Description

Could be cool if the tokeniser could be configured to specialise in HTML, or French, or whatever PL/NL.

Models could be initially pre-trained using a small vocabulary and fine-tuned to adapt to a bigger, more specialised vocabulary.

This relates to dataset construction more than actual algorithm? Or actually we might need a tool to merge to vocabs or some procedure to have a base vocab which includes "optional" tokens.

Anyway, I think this feature is more complex than it sounds but it's required for CodeGeeX Nano to be able to specialise in specific languages.

**Comment by rojas-diego** [comment]
Not a focus right now
